import { PRODUCT_CATEGORIES, type Product, type ProductCategory } from '@/types/product'

export const PRODUCT_CATEGORY_OPTIONS: ReadonlyArray<{ value: ProductCategory; label: string }> = [
  { value: PRODUCT_CATEGORIES.CLASSIC_CAKES, label: 'Tortas clásicas' },
  { value: PRODUCT_CATEGORIES.CUSTOM_CAKES, label: 'Tortas personalizadas' },
  { value: PRODUCT_CATEGORIES.CUSTOM_COOKIES, label: 'Galletas personalizadas' },
  { value: PRODUCT_CATEGORIES.BOXES, label: 'Boxes' },
]

/** Precios provisionales: editar este archivo al actualizar el catálogo. */
export const PRODUCTS: Product[] = [
  {
    id: 'super-chocotorta-premium',
    slug: 'super-chocotorta-premium',
    name: 'Super Chocotorta',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 25000,
    imagePrimary: '/images/chocotorta_3.png',
    imageSecondary: '/images/chocotorta_2.png',
    description: 'La versión más cuidada de un favorito argentino, con presentación Giuliett.',
    gallery: ['/images/chocotorta_3.png', '/images/chocotorta_2.png', '/images/chocotorta.png'],
  },
  {
    id: 'marquise',
    slug: 'marquise',
    name: 'Marquise',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 24000,
    imagePrimary: '/images/marquise.png',
    imageSecondary: '/images/marquise_2.png',
    description: 'Base intensa de chocolate, crema suave y una terminación delicada para compartir.',
    gallery: ['/images/marquise.png', '/images/marquise_2.png'],
  },
  {
    id: 'ny-cheesecake',
    slug: 'ny-cheesecake',
    name: 'NY Cheesecake',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 26000,
    imagePrimary: '/images/NY_CHEESECAKE.png',
    imageSecondary: '/images/producto-mesas.png',
    description: 'Clásico neoyorquino de textura sedosa, elaborado en pequeños lotes.',
    gallery: ['/images/NY_CHEESECAKE.png', '/images/producto-mesas.png'],
  },
  {
    id: 'lemon-pie',
    slug: 'lemon-pie',
    name: 'Lemon Pie',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 22000,
    imagePrimary: '/images/lemon.png',
    imageSecondary: '/images/lemon_2.png',
    description: 'Limón fresco, merengue ligero y una base crocante hecha a mano.',
    gallery: ['/images/lemon.png', '/images/lemon_2.png'],
  },
  {
    id: 'tarta-casha',
    slug: 'tarta-casha',
    name: 'Tarta Cabsha',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 23000,
    imagePrimary: '/images/cabsha.png',
    imageSecondary: '/images/cabsha_2.png',
    description: 'Una tarta de capas suaves y sabor equilibrado para una sobremesa especial.',
    gallery: ['/images/cabsha.png', '/images/cabsha_2.png'],
  },
  {
    id: 'chocotorta-premium',
    slug: 'chocotorta-premium',
    name: 'Chocotorta Premium',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 25000,
    imagePrimary: '/images/chocotorta_premium.png',
    imageSecondary: '/images/chocotorta_premium_2.png',
    description: 'La versión más cuidada de un favorito argentino, con presentación Giuliett.',
    gallery: ['/images/chocotorta_premium.png', '/images/chocotorta_premium_2.png', '/images/chocotorta_premium_3.png'],
  },
  {
    id: 'bomba-oreo',
    slug: 'bomba-oreo',
    name: 'Bomba Oreo',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 24000,
    imagePrimary: '/images/OREO.png',
    imageSecondary: '/images/OREO_2.png',
    description: 'Chocolate, crema y galletas en una composición intensa y generosa.',
    gallery: ['/images/OREO.png', '/images/OREO_2.png'],
  },
  {
    id: 'tarta-frutilla',
    slug: 'tarta-frutilla',
    name: 'Tarta de Frutilla',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 23000,
    imagePrimary: '/images/frutilla.png',
    imageSecondary: '/images/frutilla_2.png',
    description: 'Frutillas, crema y una base delicada para disfrutar en temporada.',
    gallery: ['/images/frutilla.png', '/images/frutilla_2.png'],
  },
  {
    id: 'turron-aleman',
    slug: 'turron-aleman',
    name: 'Turrón Alemán',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 27000,
    imagePrimary: '/images/producto-kits.png',
    imageSecondary: '/images/manifiesto-manos.png',
    description: 'Capas de textura y sabor, inspiradas en la pastelería tradicional.',
    gallery: ['/images/producto-kits.png', '/images/manifiesto-manos.png'],
  },
  {
    id: 'torta-butter',
    slug: 'torta-butter',
    name: 'Torta de Butter',
    category: PRODUCT_CATEGORIES.CUSTOM_CAKES,
    price: 38000,
    imagePrimary: '/images/producto-mesas.png',
    imageSecondary: '/images/cierre-mesa-dulce.png',
    description: 'Diseñada a medida para celebrar: sabores, colores y terminaciones a elección.',
    gallery: ['/images/producto-mesas.png', '/images/cierre-mesa-dulce.png'],
  },
  {
    id: 'torta-letter',
    slug: 'torta-letter',
    name: 'Letter Cake',
    category: PRODUCT_CATEGORIES.CUSTOM_CAKES,
    price: 38000,
    imagePrimary: '/images/letter.png',
    imageSecondary: '/images/letter_2.png',
    description: 'Diseñada a medida para celebrar: sabores, colores y terminaciones a elección.',
    gallery: ['/images/letter.png', '/images/letter_2.png'],
  },
  {
    id: 'torta-cumple',
    slug: 'torta-cumple',
    name: 'Torta de Cumpleaños',
    category: PRODUCT_CATEGORIES.CUSTOM_CAKES,
    price: 38000,
    imagePrimary: '/images/HB.png',
    imageSecondary: '/images/HB_3.png',
    description: 'Diseñada a medida para celebrar: sabores, colores y terminaciones a elección.',
    gallery: ['/images/HB.png', '/images/HB_3.png', '/images/HB_2.png', '/images/HB_4.png', '/images/HB_5.png'],
  },
  {
    id: 'torta-funny',
    slug: 'torta-funny',
    name: 'Torta Divertida',
    category: PRODUCT_CATEGORIES.CUSTOM_CAKES,
    price: 38000,
    imagePrimary: '/images/chocotorta_funny.png',
    imageSecondary: '/images/chocotorta_funny_2.png',
    description: 'Diseñada a medida para celebrar: sabores, colores y terminaciones a elección.',
    gallery: ['/images/chocotorta_funny.png', '/images/chocotorta_funny_2.png'],
  },
  {
    id: 'galletas-artesanales',
    slug: 'galletas-artesanales',
    name: 'Galletas Artesanales',
    category: PRODUCT_CATEGORIES.CUSTOM_COOKIES,
    price: 18000,
    imagePrimary: '/images/producto-cookies.png',
    imageSecondary: '/images/manifiesto-manos.png',
    description: 'Galletas horneadas y decoradas una por una para hacer memorable cada detalle.',
    gallery: ['/images/producto-cookies.png', '/images/manifiesto-manos.png'],
  },
  {
    id: 'box-cookies',
    slug: 'box-cookies',
    name: 'Box Cookies',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 16000,
    imagePrimary: '/images/BOX_COOKIES.png',
    imageSecondary: '/images/producto-cookies.png',
    description: 'Una selección de cookies artesanales presentada para regalar o compartir.',
    gallery: ['/images/BOX_COOKIES.png', '/images/producto-cookies.png'],
  },
  {
    id: 'box-macarons',
    slug: 'box-macarons',
    name: 'Box Macarons',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 19000,
    imagePrimary: '/images/MACARONS.png',
    imageSecondary: '/images/MACARONS_2.png',
    description: 'Macarons de receta francesa en una caja pensada para sorprender.',
    gallery: ['/images/MACARONS.png', '/images/MACARONS_2.png'],
  },
  {
    id: 'box-parisino',
    slug: 'box-parisino',
    name: 'Box Parisino',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 22000,
    imagePrimary: '/images/BOX.png',
    imageSecondary: '/images/BOX_2.png',
    description: 'Una experiencia de sabores y detalles delicados con acento parisino.',
    gallery: ['/images/BOX.png', '/images/BOX_2.png'],
  },
  {
    id: 'box-souvenirs',
    slug: 'box-souvenirs',
    name: 'Box Souvenirs',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 22000,
    imagePrimary: '/images/souvenirs.png',
    imageSecondary: '/images/souvenirs_2.png',
    description: 'Una experiencia de sabores y detalles delicados con acento parisino.',
    gallery: ['/images/souvenirs.png', '/images/souvenirs_2.png', '/images/souvenirs_3.png'],
  },
]

export function isProductCategory(value: string | null): value is ProductCategory {
  return PRODUCT_CATEGORY_OPTIONS.some((category) => category.value === value)
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((product) => product.slug === slug)
}
