import { PRODUCT_CATEGORIES, type Product, type ProductCategory } from '@/types/product'

export const PRODUCT_CATEGORY_OPTIONS: ReadonlyArray<{ value: ProductCategory; label: string }> = [
  { value: PRODUCT_CATEGORIES.CLASSIC_CAKES, label: 'Tortas clásicas' },
  { value: PRODUCT_CATEGORIES.CUSTOM_CAKES, label: 'Tortas personalizadas' },
  { value: PRODUCT_CATEGORIES.CUSTOM_COOKIES, label: 'Galletas personalizadas' },
  { value: PRODUCT_CATEGORIES.BOXES, label: 'Boxes' },
]

/** Precios provisionales: editar este archivo al actualizar el catálogo. */
export const PRODUCTS: Product[] = [
  {
    id: 'marquise',
    slug: 'marquise',
    name: 'Marquise',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 24000,
    imagePrimary: '/images/producto-cookies.png',
    imageSecondary: '/images/cierre-mesa-dulce.png',
    description: 'Base intensa de chocolate, crema suave y una terminación delicada para compartir.',
    gallery: ['/images/producto-cookies.png', '/images/cierre-mesa-dulce.png'],
  },
  {
    id: 'ny-cheesecake',
    slug: 'ny-cheesecake',
    name: 'NY Cheesecake',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 26000,
    imagePrimary: '/images/producto-macarons.png',
    imageSecondary: '/images/producto-mesas.png',
    description: 'Clásico neoyorquino de textura sedosa, elaborado en pequeños lotes.',
    gallery: ['/images/producto-macarons.png', '/images/producto-mesas.png'],
  },
  {
    id: 'lemon-pie',
    slug: 'lemon-pie',
    name: 'Lemon Pie',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 22000,
    imagePrimary: '/images/manifiesto-manos.png',
    imageSecondary: '/images/hero-caja-cookies.png',
    description: 'Limón fresco, merengue ligero y una base crocante hecha a mano.',
    gallery: ['/images/manifiesto-manos.png', '/images/hero-caja-cookies.png'],
  },
  {
    id: 'tarta-casha',
    slug: 'tarta-casha',
    name: 'Tarta Casha',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 23000,
    imagePrimary: '/images/producto-mesas.png',
    imageSecondary: '/images/producto-macarons.png',
    description: 'Una tarta de capas suaves y sabor equilibrado para una sobremesa especial.',
    gallery: ['/images/producto-mesas.png', '/images/producto-macarons.png'],
  },
  {
    id: 'chocotorta-premium',
    slug: 'chocotorta-premium',
    name: 'Chocotorta Premium',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 25000,
    imagePrimary: '/images/cierre-mesa-dulce.png',
    imageSecondary: '/images/producto-kits.png',
    description: 'La versión más cuidada de un favorito argentino, con presentación Giuliett.',
    gallery: ['/images/cierre-mesa-dulce.png', '/images/producto-kits.png'],
  },
  {
    id: 'bomba-oreo',
    slug: 'bomba-oreo',
    name: 'Bomba Oreo',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 24000,
    imagePrimary: '/images/hero-caja-cookies.png',
    imageSecondary: '/images/producto-cookies.png',
    description: 'Chocolate, crema y galletas en una composición intensa y generosa.',
    gallery: ['/images/hero-caja-cookies.png', '/images/producto-cookies.png'],
  },
  {
    id: 'tarta-frutilla',
    slug: 'tarta-frutilla',
    name: 'Tarta de Frutilla',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 23000,
    imagePrimary: '/images/producto-macarons.png',
    imageSecondary: '/images/cierre-mesa-dulce.png',
    description: 'Frutillas, crema y una base delicada para disfrutar en temporada.',
    gallery: ['/images/producto-macarons.png', '/images/cierre-mesa-dulce.png'],
  },
  {
    id: 'turron-aleman',
    slug: 'turron-aleman',
    name: 'Turrón Alemán',
    category: PRODUCT_CATEGORIES.CLASSIC_CAKES,
    price: 27000,
    imagePrimary: '/images/producto-kits.png',
    imageSecondary: '/images/manifiesto-manos.png',
    description: 'Capas de textura y sabor, inspiradas en la pastelería tradicional.',
    gallery: ['/images/producto-kits.png', '/images/manifiesto-manos.png'],
  },
  {
    id: 'torta-butter',
    slug: 'torta-butter',
    name: 'Torta de Butter',
    category: PRODUCT_CATEGORIES.CUSTOM_CAKES,
    price: 38000,
    imagePrimary: '/images/producto-mesas.png',
    imageSecondary: '/images/cierre-mesa-dulce.png',
    description: 'Diseñada a medida para celebrar: sabores, colores y terminaciones a elección.',
    gallery: ['/images/producto-mesas.png', '/images/cierre-mesa-dulce.png'],
  },
  {
    id: 'galletas-artesanales',
    slug: 'galletas-artesanales',
    name: 'Galletas Artesanales',
    category: PRODUCT_CATEGORIES.CUSTOM_COOKIES,
    price: 18000,
    imagePrimary: '/images/producto-cookies.png',
    imageSecondary: '/images/manifiesto-manos.png',
    description: 'Galletas horneadas y decoradas una por una para hacer memorable cada detalle.',
    gallery: ['/images/producto-cookies.png', '/images/manifiesto-manos.png'],
  },
  {
    id: 'box-cookies',
    slug: 'box-cookies',
    name: 'Box Cookies',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 16000,
    imagePrimary: '/images/hero-caja-cookies.png',
    imageSecondary: '/images/producto-cookies.png',
    description: 'Una selección de cookies artesanales presentada para regalar o compartir.',
    gallery: ['/images/hero-caja-cookies.png', '/images/producto-cookies.png'],
  },
  {
    id: 'box-macarons',
    slug: 'box-macarons',
    name: 'Box Macarons',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 19000,
    imagePrimary: '/images/producto-macarons.png',
    imageSecondary: '/images/producto-kits.png',
    description: 'Macarons de receta francesa en una caja pensada para sorprender.',
    gallery: ['/images/producto-macarons.png', '/images/producto-kits.png'],
  },
  {
    id: 'box-parisino',
    slug: 'box-parisino',
    name: 'Box Parisino',
    category: PRODUCT_CATEGORIES.BOXES,
    price: 22000,
    imagePrimary: '/images/producto-kits.png',
    imageSecondary: '/images/cierre-mesa-dulce.png',
    description: 'Una experiencia de sabores y detalles delicados con acento parisino.',
    gallery: ['/images/producto-kits.png', '/images/cierre-mesa-dulce.png'],
  },
]

export function isProductCategory(value: string | null): value is ProductCategory {
  return PRODUCT_CATEGORY_OPTIONS.some((category) => category.value === value)
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((product) => product.slug === slug)
}
